#!/bin/bash
# Batch-extract OoT rooms, collision, and transitions from ROM.
# Extracts ALL rooms per scene (not just room_0).
# Generates cd.xml for mkpsxiso.
# Usage: bash tools/extract_rooms.sh /path/to/oot.z64

set -e

ROM="$1"
if [ -z "$ROM" ]; then
    echo "Usage: $0 <rom_path>"
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT="$SCRIPT_DIR/.."
OUTDIR="$PROJECT/data/rooms"
COLDIR="$PROJECT/data/collision"
TRNDIR="$PROJECT/data/transitions"
mkdir -p "$OUTDIR" "$COLDIR" "$TRNDIR"

EXTRACT="$SCRIPT_DIR/extract_room.py"

# Scene definitions (prefix used in DMA table entries)
SCENES=(
    ydan
    spot04
    spot00
    Bmori1
    HIDAN
    MIZUsin
    HAKAdan
    spot15
    spot01
)

# Clean old room files to avoid stale data
rm -f "$OUTDIR"/*.prm "$COLDIR"/*.col "$TRNDIR"/*.trn

TOTAL_ROOMS=0

for scene in "${SCENES[@]}"; do
    echo "=== Scene: $scene ==="

    # Extract collision (once per scene, using room_0 to auto-detect scene file)
    echo "  Extracting collision..."
    python3 "$EXTRACT" "$ROM" "${scene}_room_0" \
        --col "$COLDIR/${scene}.col" 2>&1 | grep -E "(COL v1|Collision:|Bounds:)" || {
        echo "  [WARN] Collision extraction failed for $scene"
    }

    # Extract transitions
    echo "  Extracting transitions..."
    python3 "$EXTRACT" "$ROM" "${scene}_room_0" \
        --trn "$TRNDIR/${scene}.trn" 2>&1 | grep -E "(TRN v1|Transitions:)" || {
        echo "  [WARN] Transition extraction failed for $scene"
    }

    # Extract all rooms (loop until DMA entry not found)
    room_idx=0
    while true; do
        room_name="${scene}_room_${room_idx}"
        output="$OUTDIR/${room_name}.prm"
        # Try extraction; if the room DMA entry doesn't exist, break
        if python3 "$EXTRACT" "$ROM" "$room_name" \
               --prm "$output" 2>&1 | grep -q "PRM v2"; then
            size=$(ls -lh "$output" 2>/dev/null | awk '{print $5}')
            echo "  Room $room_idx: $room_name ($size)"
            room_idx=$((room_idx + 1))
        else
            break
        fi
    done
    echo "  → $room_idx rooms extracted for $scene"
    TOTAL_ROOMS=$((TOTAL_ROOMS + room_idx))
    echo ""
done

# Extract Link's skeletal mesh + animations
echo "=== Extracting Link skeleton ==="
SKEL_OUT="$PROJECT/data/link.skm"
python3 "$SCRIPT_DIR/extract_skeleton.py" "$ROM" --skm "$SKEL_OUT" 2>&1 | tail -3 || {
    echo "  [WARN] Failed to extract skeleton"
}
echo ""

# ── Generate cd.xml ──────────────────────────────────────────────────────────
echo "=== Generating cd.xml ==="

# Map scene prefix to uppercase CD-ROM prefix for filenames
# e.g. ydan_room_0.prm → YDAN_0.PRM, MIZUsin_room_0.prm → MIZUSIN_0.PRM
cd_name() {
    local base="$1"       # e.g. ydan_room_0
    local scene="${base%_room_*}"   # e.g. ydan
    local room="${base##*_room_}"   # e.g. 0
    local upper
    upper=$(echo "$scene" | tr '[:lower:]' '[:upper:]')
    echo "${upper}_${room}"
}

CDXML="$PROJECT/cd.xml"

cat > "$CDXML" << 'XMLHEAD'
<?xml version="1.0" encoding="UTF-8"?>
<!-- mkpsxiso disc layout for OoT PS1 port (auto-generated by extract_rooms.sh) -->
<iso_project image_name="oot.bin" cue_sheet="oot.cue">
  <track type="data">
    <identifiers
      system        ="PLAYSTATION"
      application   ="PLAYSTATION"
      volume        ="OOT"
      volume_set    ="OOT"
      publisher     =""
      data_preparer =""
    />
    <directory_tree>
      <file name="SYSTEM.CNF" source="SYSTEM.CNF"/>
      <file name="OOT.EXE"    source="build/oot.ps-exe"/>
      <file name="LINK.SKM"   source="data/link.skm"/>
      <dir name="ROOMS">
XMLHEAD

# Add all PRM files sorted by scene order then room number
for scene in "${SCENES[@]}"; do
    room_idx=0
    while true; do
        room_name="${scene}_room_${room_idx}"
        prm_file="$OUTDIR/${room_name}.prm"
        if [ -f "$prm_file" ]; then
            cdname=$(cd_name "$room_name")
            printf '        <file name="%s.PRM" source="data/rooms/%s.prm"/>\n' \
                "$cdname" "$room_name" >> "$CDXML"
            room_idx=$((room_idx + 1))
        else
            break
        fi
    done
done

cat >> "$CDXML" << 'XMLMID1'
      </dir>
      <dir name="COL">
XMLMID1

# Add collision files
for scene in "${SCENES[@]}"; do
    col_file="$COLDIR/${scene}.col"
    if [ -f "$col_file" ]; then
        upper=$(echo "$scene" | tr '[:lower:]' '[:upper:]')
        printf '        <file name="%s.COL" source="data/collision/%s.col"/>\n' \
            "$upper" "$scene" >> "$CDXML"
    fi
done

cat >> "$CDXML" << 'XMLMID2'
      </dir>
      <dir name="TRN">
XMLMID2

# Add transition files
for scene in "${SCENES[@]}"; do
    trn_file="$TRNDIR/${scene}.trn"
    if [ -f "$trn_file" ]; then
        upper=$(echo "$scene" | tr '[:lower:]' '[:upper:]')
        printf '        <file name="%s.TRN" source="data/transitions/%s.trn"/>\n' \
            "$upper" "$scene" >> "$CDXML"
    fi
done

cat >> "$CDXML" << 'XMLTAIL'
      </dir>
    </directory_tree>
  </track>
</iso_project>
XMLTAIL

echo "  Generated $CDXML"
echo ""

# ── Summary ──────────────────────────────────────────────────────────────────
echo "=== Summary ==="
echo "  Rooms:       $TOTAL_ROOMS PRM files"
echo "  Collision:   $(ls "$COLDIR"/*.col 2>/dev/null | wc -l | tr -d ' ') COL files"
echo "  Transitions: $(ls "$TRNDIR"/*.trn 2>/dev/null | wc -l | tr -d ' ') TRN files"
echo ""
echo "Room files:"
ls -lhS "$OUTDIR"/*.prm 2>/dev/null | head -20
echo "..."
echo "Total: $(du -sh "$OUTDIR" | awk '{print $1}')"
